# Generated by Django 2.2.7 on 2019-11-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.IntegerField()),
                ('contact_info', models.CharField(max_length=100)),
            ],
        ),
    ]
