# Generated by Django 2.2.7 on 2019-11-09 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_descr', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_url', models.CharField(max_length=300)),
                ('reference_name', models.CharField(max_length=20)),
                ('reference_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_file', models.ImageField(upload_to='')),
                ('picture_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Project')),
            ],
        ),
    ]
