# Generated by Django 2.2.7 on 2019-11-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_picture_project_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture_file',
            field=models.ImageField(upload_to='./main_app/media'),
        ),
    ]
